repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 25.12.0  # ТА ЖЕ версия что и локально
    hooks:
      - id: black
        name: black (check only)
        files: ^backend/
        args: [ --line-length=119, --check]  # ← ТОЛЬКО ПРОВЕРКА, без изменений
        stages: [commit]
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        files: ^backend/
        args: [--max-line-length=119, --max-complexity=10]
        stages: [commit]
